
:Author: plouc68000
:Email: plouc68000@gmail.com
:Date: 14/10/2018
:Revision: ArduTester V1.13
:License: OSHW

= Project: {Project}
Porting of the files from TransistorTester V1.13 in the Arduino Editor, 
porting first to Arduino Mega, then to Arduino UNO.



== Step 3: Load the code

Select Arduino/Genuino Uno and
Upload the code contained in this sketch on to your board

=== Folder structure

....
 TT_1_13_UNO             => Arduino sketch folder
  ├── TT_13oct.ino       => main Arduino file
  ├── schematics.png     => (optional) if someone wants to do it ...
  ├── layout.png         => (optional) if someone wants to do it ...
  └── ReadMe.adoc        => this file
....

=== License
This project is released under a {OSHW} License.

=== Contributing
To contribute to this project please contact plouc68000 <plouc68000@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name           | Part number | Quantity
|    | Arduino UNO R3      |             | 1       
|    | LCD Module 1602     |             | 1        
|    | Resistor 680 Ohm    |             | 3   
|    | Resistor 470 kOhm   |             | 3
|    | Resistor 10  kOhm   |             | 1
|    | Pot. 10 kOhm        |             | 1
|    | Test Button         |             | 1  
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
